project:
  type: book
  output-dir: "./docs"

book:
  title: "Research Toolkit"
  author: "Nikita Tkachenko"
  date: today
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/summary.qmd
    - chapters/setup.qmd
    - chapters/repres.qmd
    - chapters/version_control.qmd
    - part: "Lit Review and Writing"
      chapters:
        - chapters/litreview.qmd
        - chapters/write.qmd
        - chapters/layout_refs.qmd
        - chapters/template.qmd
        - chapters/collaboration.qmd
    - part: "Collecting the Data"
      chapters:
      # Survey Standard Error
      # Survey Design Tools
      # What Questions to use
      # Google APIs
      # Building a Data Base in Google Sheets
      # Creating Code Book and Documentation + Flow Charts
        - chapters/qualtrics_api.qmd
    - part: "Working with Data"
      chapters:
        - chapters/data_manipulation.qmd
        - chapters/tidy_data.qmd
        - chapters/data_bases.qmd
        # cleaning(dealing with NAs), validation, export
    - part: "Presenting the Data"
      chapters:
        - chapters/data_viz.qmd
        - chapters/color.qmd
        - chapters/which_graph.qmd # add corelation matrix plots, and ggmargins
        # How to make good looking tables 
    - part: "Power Analysis and Simulations"
        # Power Analysis and Simulations
        # Modeling 
        # Vizualizing models and model assumptions
    - chapters/references.qmd
 # repo-actions: [edit, issue]
  repo-url: https://github.com/nikitoshina/quarto_book
 # issue-url: https://github.com/nikitoshina/quarto_book/issues/new/choose
 

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-before-body: reading-time.html
    
 # pdf:
  #  documentclass: book
comments:
  giscus: 
    repo: nikitoshina/quarto_book

reference-location: margin
citation-location: margin

