---
title: "Setting Up R and RStudio"
---

```{r}
#| include: false
source("../scripts/knitr-minted-listed-hook.r")
```


Welcome to the exciting world of data analysis with R, a language crafted specifically for statistical analysis and data visualization. R's user-friendly syntax and reproducibility make it an ideal choice for both novices and professionals. However, before diving into data exploration and modeling, it's essential to differentiate between R, the programming language, and RStudio, the Integrated Development Environment (IDE) that enhances R's functionality.

## Download and Install R

R is maintained and distributed through The Comprehensive R Archive Network (CRAN), ensuring you have access to the latest version and resources.

### For macOS Users:

1. Navigate to the [CRAN website](https://cran.r-project.org/).
2. Click on "Download R for macOS".
3. Select the appropriate version:
   - For Apple Silicon (M1, M2, etc.), download the version labeled with "-arm64" (e.g., R-4.2.2-arm64.pkg).
   - For Intel-based Macs, select the version without "-arm64" (e.g., R-4.2.2.pkg).
4. Follow the installation wizard. The default settings are typically sufficient.

### For Windows Users:

1. Visit the [CRAN website](https://cran.r-project.org/).
2. Choose "Download R for Windows".
3. Select "base" and then the first link at the top of the page (e.g., Download R-4.2.2 for Windows).
4. The installer will guide you through the process. Stick with the default settings for a smooth installation.
5. Additionally, Windows users should download Rtools, crucial for compiling packages from source. Visit [Rtools](https://cran.r-project.org/bin/windows/Rtools/), match the Rtools version with your R version, and follow the installer instructions.

## Download and Install RStudio

RStudio provides a user-friendly interface for R, akin to what Microsoft Word offers for text but tailored for R scripting.

- To download RStudio, head to the [RStudio Download Page](https://posit.co/download/rstudio-desktop/).
- Click on "DOWNLOAD RSTUDIO" or select your operating system for detailed instructions.

## Configure RStudio

Enhance your RStudio experience with these initial setup tips:

- **Change Theme**: Shift from the default theme to a dark theme for improved readability. Go to `Tools` > `Global Options` > `Appearance`, and select "Dracula". Click "Apply".
- **Install Fira Code Font**: For a modern coding aesthetic, install the "Fira Code" font, which supports programming ligatures. Instructions can be found at [Fira Code on GitHub](https://github.com/tonsky/FiraCode/wiki/Installing). After installation, apply this font in RStudio under `Appearance`.

## Install Packages

Packages extend R's functionality. Install them easily with commands in the RStudio console:

```r
# Install a single package
install.packages("tidyverse")

# Install multiple packages
install.packages(c("tidyverse", "gapminder"))
```

To use installed packages, load them into your session:

```r
library(tidyverse)
```

Now that we have R and RStudio up and running, let's dive into some fundamental data manipulation techniques in R.
