---
title: "Version Control with Git and Github"
editor: visual
---

Picture yourself working tirelessly on your thesis or a final paper. You've invested days in brainstorming ideas, writing the story, coding, reviewing, and adding visuals. After hours of refining, it's nearly perfect -- until your trusty laptop decides to self-destruct. If only you'd saved your work online, you wouldn't be scrambling to find the latest emailed version or rewriting from a printed copy annotated by your advisor. Or even worse, starting from scratch! \~ based on my story.

Undeterred, you begin storing everything on Google Drive, thinking you're now safe. You tackle a big coding project, crafting an impressive model with a sleek frontend. But when you try to neaten your messy code, the entire application crashes and becomes a bug-infested nightmare. If only there was an easy way to revert to a previous version, or work on new changes without disrupting the main codebase... \~ another life story of mine.

If any of this sounds familiar, I feel your pain. But if not, it's not too late to prevent such catastrophes with version control! Picture version control as the ultimate folder with labels like "final_version," "final_version2.0," and "final_final_version1.2.5." It tracks every change you make to documents, code, and data files, acting like a time machine that whisks you back to any point in your project's history. With it, you can recover any previous version of your work. Sounds like magic, right?

Here's how version control works:

1.  **Snapshots**: Every time you save your work, version control takes a snapshot, preserving that particular version with a comment on what you did.

2.  **Branching**: Want to try out a bold new idea, but afraid it might not work? No problem! With version control, you can create a separate "branch" and experiment without affecting the main version. If your idea works, you can "merge" the changes back into the main branch. If not, just discard the experimental branch and pretend it never happened.

3.  **Collaboration**: Working with a team? Version control makes collaborating a breeze. Each team member can work on their part of the project, and later "merge" all the changes into a cohesive whole. Replacing the email chains with "Final_Version_3\_revised_edited_FINAL_review".

4.  **Backup**: Version control also acts as a backup system, ensuring your work is safely stored in a remote location. So even if your computer decides to give up on you, your project remains secure and accessible.

## Git and Github

Git is a widely-used version control system that efficiently manages and distributes projects of various sizes and complexities. Essential for developers, scientists, analysts, and writers, Git excels in tracking changes, fostering collaboration, and handling code. As a command-line interface, Git is accessed via the terminal.

GitHub, a web-based platform, enhances Git's functionality by offering a user-friendly interface for project management and collaboration. Additional features include issue tracking, code review, and project management tools. GitHub also serves as a developer's social network, facilitating the sharing of work, discovery of projects, and open-source contributions.


> The difference between Git and GitHub is the same as the difference between Porn and PornHub.


Starting to use Git and GitHub can be a little overwhelming and confusing, especially when you only need a small subset of the functionality. My goal is to make you feel comfortable enough with the basics, so you can store, update, collaborate, and share your work on GitHub.

There have been many guides on installing Git on your machine and connecting it to RStudio. I will spare the world from my version. I recommend you use the guide from @hesterLetGitStarted [Happy Git and GitHub for the useR](https://happygitwithr.com/index.html) and use it as a reference for your other adventures with Git. Once you went through the whole process of installation. You may want to connect it to RStudio; however, it is optional. Because the commands can be hard to memorize and connect to the actions and the state of your repository, you should install a Git Client, which will get an overview of the recent commit history, branches, and a GUI that simplifies Git operations. Try [GitHub Destop](https://desktop.github.com/) or [GitKraken](https://www.gitkraken.com/).

> When inside of repository press "." to start web version of VSCode to work with the repository.

## Basics

Repositories on GitHub are storage spaces for your projects, where you can manage, organize, and collaborate on files while keeping track of changes using Git's version control system. To create a repository you can start with GitHub first or Local first. In other words, with GitHub first you start by initiating a repository on GitHub and then cloning it into your machine and with Local First you write somecode and connect your repository to the GitHub. I am generally using Local First as I often start the project and later decide whether I want it online. With GitHub desktop it is extremely easy to add a repo by just going to File -\> New Repository. There are also two types of repositories Private and Public. You can change the status in your repository's settings.

Say you have done some work and want to save it. You want to commit! To do that select all the file you want to add to the commit `git add file.md` or add all files with `git add .` and then `git commit -m "message"`, it is required to add a message to your commit, so you don't forget what changes you made. All of this can be done in your client and even RStudio with a click of few buttons. Nonetheless, I advise you get comfortable with using Command Line Interface (CLI). Now you have committed the changes, but they are not yet online, they are just recorded, so you can load them if you mess up. You can have multiple commits to keep on adding more and more changes before you are ready to share your work with the world. Once you are ready you want to `git push` and everything will appear on your GitHub!

What if you want to download the version from GitHub, say you want to work on a different machine? 'Git pull' is a command that combines fetching updates from a remote repository and merging them into your local branch. It also allows you to synchronize your local branch with the latest changes from the remote, ensuring your project stays up-to-date and facilitating collaboration with other contributors.

But what happens if your partner updates the version on GitHub while you are working? Now you need somehow incorporate the changes into your work. To do that you first pull and if there are no conflicts, you didn't change the same line, it will automatically merge both versions. But what if you worked on the document and there were conflicts? You need to resolve them, just like in middle school.

Resolving a merge conflict in Git involves identifying the conflicting changes and manually deciding which changes to keep or modify inside the file with the conflict. It will be depicted like this inside the file:

```         
<<<<<<< HEAD
This is the line in your current branch
========
This is the line in the branch you're merging.
>>>>>>> <branch-name>
```

To resolve the conflict, edit the file to keep the desired changes and remove the conflict markers. You might keep the change from the current branch, the branch you're merging, or create a new line altogether:

```         
This is the new, resolved line.
```

Save the changes in the file and stage the file using `git add`. Commit the resolved merge conflict with `git commit -m "Resolved merge conflict in file"`.

Recall when my attempt to tidy code caused a crash (second story)? To prevent this, use branches in Git. Branches let you work on multiple features or fixes without affecting the main codebase. Once complete and tested, merge the branch back into the main branch.

Forking creates a personal copy of a repository under your account, while cloning creates a local copy on your computer. Forking is popular in open-source projects, allowing contributors to make changes without affecting the original project. After testing, submit a pull request to propose updates to the original repository.

A pull request proposes merging changes from one branch to another, typically from a forked repository to the original repository. It facilitates discussion, review, and collaboration, enabling project maintainers to approve, modify, or reject proposed changes.

GitHub issues help track bugs, requests, or discussions related to a project. They serve as a centralized forum for communication, task assignment, and progress monitoring, ensuring effective project management and timely resolution of concerns.

## Contribute

GitHub streamlines collaboration on projects, offering several straightforward methods to contribute to any project. To practice, find a typo in this book and suggest an edit. Here's how:

1.  Click on the GitHub icon and navigate to the file (chapter) in the repository.
2.  Open the file and click the edit icon (pencil).
3.  Make the necessary changes, which will automatically create a fork and submit a pull request.

Alternatively, you can fork the project, clone it to your computer, make changes, and submit a pull request. Another way to suggest changes or ask questions about the material is by opening an issue and leaving a comment. This approach allows you to provide feedback and engage in discussions with other contributors.

## Guide to Using .gitignore

The `.gitignore` file instructs Git which files should not be tracked or ignored before you make a commit. It is especially useful in a team-based project where different developers have their own configurations, settings, and IDEs, or when you have temporary files that are generated when a program runs. Let's walk through how to create and manage a `.gitignore` file.

### Creating a .gitignore file

To create a `.gitignore` file, navigate to your project's root directory and create a new file named `.gitignore`. This can be done directly via your code editor or in the terminal:

```{bash}
touch .gitignore
```

### Specifying Files to Ignore

Open the `.gitignore` file in your text editor and specify the files, directories, or file patterns to ignore. Each new line should contain a new rule.

- To ignore a directory, simply add the directory name, e.g., `node_modules/`
- To ignore a file, add the full file name, e.g., `debug.log`
- To ignore a file type, use `*.` followed by the file extension, e.g., `*.log`
- Comments can be added by starting a line with a `##`, e.g., `## This is a comment`

Here's an example `.gitignore` file:

```{bash}
## Ignore node_modules directory
node_modules/

## Ignore all .log files
*.log

## Ignore the debug.log file
debug.log
```

### The Global .gitignore file

For files you'd like to ignore globally, across all projects, you can create a global `.gitignore` file:

```{bash}
git config --global core.excludesfile '~/.gitignore'
```

Now you can define all rules in the `~/.gitignore` file, and these will be applied across all repositories.

### .gitignore in Other Programs

While `.gitignore` was originated from and is most commonly associated with Git, the concept of defining files and directories to ignore has been adopted by other software tools. These tools include various integrated development environments (IDEs), text editors, and even some operating systems. Many of these tools support `.gitignore` syntax and semantics, offering a familiar way to exclude files and directories. It's always best to check the documentation of your specific tools to see how they handle file ignoring.

## Other Resources

For most programming languages and popular software tools, standard .gitignore files have been created and maintained by the open-source community. GitHub maintains a repository of these files. You can use them as a starting point for your projects.

For more complex scenarios, please refer to the official Git documentation on the `.gitignore` file.

Remember, a `.gitignore` file helps to keep your repositories clean from unnecessary files. Make good use of it!
